language: r
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "devtools::install()"
  - source shim_package.sh
  - Rscript -e 'covr::codecov()'
