# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_success:
  - sed -i -e 's/Package: covr/Package: covr_shim/' DESCRIPTION;
  - sed -i -e 's/rex::register_shortcuts("covr")/rex::register_shortcuts("covr_shim")' R/covr.R
  - Rscript -e 'covr::coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
