language: r
sudo: false
cache: packages
r:
  - oldrel
  - devel

matrix:
  include:
    r: release
    after_success:
      - R CMD INSTALL $PKG_TARBALL
      - source shim_package.sh
      - Rscript -e 'covr::codecov()'
