language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/lintr
  - jimhester/covr

before_script:
  - Rscript -e 'lintr::lint_package()'

after_success:
  - Rscript -e 'covr::codecov()'
